### ISSUE TITLE
CallBuilder.stream needs to be adapted for React Native

### ISSUE THREAD

**Issue by mikeyrf** [pigzbe/react-native-stellar-sdk#2]
js-stellar-sdk's `CallBuilder.stream` defaults to window.EventSource in RN, which will end up being undefined in the current implementation ([call_builder.js#L8](https://github.com/stellar/js-stellar-sdk/blob/master/src/call_builder.js#L8)). Overriding with a global requiring the js [eventsource](https://github.com/EventSource/eventsource) package (i.e. `global.EventSource = require('eventsource')`) won't work given [RN issue #12890](https://github.com/facebook/react-native/issues/12890).

I haven't had much success with RN's community packages for EventSource unfortunately:

- [react-native-event-source](https://github.com/jordanbyron/react-native-event-source): This polyfill still ends up raising `EventSource not supported` from js-stellar-sdk when I require the package for global.EventSource
- [react-native-eventsource](https://github.com/JonnyBGod/react-native-eventsource): This native implementation hasn't been maintained. I'm thinking of updating it as the solution

I know @abuiles came up with a solution using [node-libs-react-native](https://github.com/stellar/js-stellar-sdk/issues/162#issuecomment-407466163), but I haven't gotten this to work with [expo](https://github.com/expo/expo).

Any thoughts/help would be great thanks!

**Comment by ianmcgregor** [comment]
The `react-native-event-source` package you mentioned is included in this repo and it does seem to work. It polls the endpoint instead of streaming so not going to be as fast or efficient as a native implementation.

As you can see from this repo I ended up using Webpack to bundle the SDK with all the polyfills as I was running into various issues otherwise. [Eventsource is aliased here](https://github.com/pigzbe/react-native-stellar-sdk/blob/master/webpack.config.js#L24)

e.g.
```
server.payments()
  .cursor('now')
  .stream({
    onmessage: payment => console.log('payment:', payment)
  })
```

**Comment by mikeyrf** [comment]
Hmm .. But even with the Webpack bundle, won't the EventSource variable declaration [call_builder.js#L8](https://github.com/stellar/js-stellar-sdk/blob/master/src/call_builder.js#L8) evaluate to `window.EventSource` which will be `undefined` in React Native?

That's what I seem to be finding with my console output:

```
[16:00:57] undefined is not a constructor (evaluating 'new l(e.url.toString())')
- node_modules/@pigzbe/react-native-stellar-sdk/stellar-sdk.js:8:48460 in i
- node_modules/@pigzbe/react-native-stellar-sdk/stellar-sdk.js:8:48797 in value
* crypto/index.js:163:14 in _callee9$
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:62:44 in tryCatch
- node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:288:30 in invoke
- ... 14 more stack frames from framework internals
```

**Comment by ianmcgregor** [comment]
Yes you're right @mikeyrf -- I've realised it was only working for me because with remote debugging on (osx, simulator or attached device) window.EventSource is actually present!

Have tried the react native polyfills and they are not working at all. [This web polyfill](https://github.com/Yaffle/EventSource) is popular and maintained and it does seem to work effectively. There is one issue in that it occasionally throws an unhandled error on opening an already open XHR connection -- it carries on fine despite this but in RN that has to be swallowed by a global error handler to avoid the red screen.

**Comment by mikeyrf** [comment]
Yea the debugger with RN is misleading for the EventSource issue :(

I was actually able to get the stream to work properly, but it required forking `js-stellar-sdk` with a slight change to its EventSource import statement in [call_builder.js#L9](https://github.com/mikeyrf/js-stellar-sdk/blob/master/src/call_builder.js#L9).

There's also a tiny bug in `react-native-event-source` with an undeclared var `retry`, so I went ahead and forked that repo too, making a small correction in [EventSource.js#L71](https://github.com/mikeyrf/react-native-event-source/blob/master/EventSource.js#L71).

I'll likely put in pull requests for these changes to the parent repos, but otherwise feel free to use my forks. They're working for me in the js-stellar-sdk + react-native-event-source + react-native-stellar-sdk setup.
